### ISSUE TITLE
Blog images should be organized into folders

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus-website#7]
For each blog post, a separate folder should be created to store the blog's images.

**Comment by alidevjimmy** [comment]
There is no limitation to doing it.
what only matters is that images should take place under /assets directory.

**Comment by alidevjimmy** [comment]
> All blog post assets, including images, should be organized inside the blog folder, like this:
> 
> like `images/blog/<file-name-without-.md>/img-1.png` 

Ok, I'll organize them.
